/**
 * AI Adapter layer (docs/5: AI要約フロー設計 §11)
 *
 * Defines the interface for generating AI summaries.
 * Current implementation is a mock. Swap `MockAiAdapter` for a real
 * implementation (OpenAI, Gemini, etc.) without changing the caller.
 */

export interface AlertSummaryContext {
  alertEventId: string;
  alertName: string;
  alertType: string | null;
  timeframe: string | null;
  triggerPrice: number | null;
  triggeredAt: Date | null;
  symbol: {
    id: string;
    displayName: string | null;
    tradingviewSymbol: string | null;
    marketCode: string | null;
  } | null;
  rawPayload: Record<string, unknown>;
  // External references collected before summary generation (docs/6 §15, docs/10 §6 reference_ids)
  referenceIds: string[];
  references: Array<{
    id: string;
    referenceType: string;
    sourceType?: string;
    title: string;
    sourceName: string | null;
    sourceUrl: string | null;
    publishedAt: Date | null;
    publishedAtIso?: string | null;
    summaryText: string | null;
    relevanceScore: number | null;
  }>;
}

export interface AlertSummaryOutput {
  title: string;
  bodyMarkdown: string;
  // structured_json — full wrapper per docs/10 §4 common wrapper
  structuredJson: {
    schema_name: 'alert_reason_summary';
    schema_version: '1.0';
    confidence: 'high' | 'medium' | 'low';
    insufficient_context: boolean;
    payload: {
      what_happened: string;
      fact_points: string[];
      reason_hypotheses: { text: string; confidence: string; reference_ids: string[] }[];
      watch_points: string[];
      next_actions: string[];
      reference_ids: string[];
    };
  };
  modelName: string;
  promptVersion: string;
}

export interface AiAdapter {
  generateAlertSummary(context: AlertSummaryContext): Promise<AlertSummaryOutput>;
}

// ─── Mock Adapter ──────────────────────────────────────────────────────────
// Used for development / CI. Replace with a real adapter for production.

export class MockAiAdapter implements AiAdapter {
  readonly modelName = 'mock-v1';
  readonly promptVersion = 'v1.0.0-mock';

  async generateAlertSummary(ctx: AlertSummaryContext): Promise<AlertSummaryOutput> {
    // Simulate processing time
    await new Promise((r) => setTimeout(r, 50));

    const symbolLabel = ctx.symbol?.displayName ?? ctx.symbol?.tradingviewSymbol ?? 'Unknown Symbol';
    const priceInfo = ctx.triggerPrice ? ` (trigger price: ${ctx.triggerPrice})` : '';
    const timeInfo = ctx.triggeredAt ? ctx.triggeredAt.toISOString() : 'N/A';
    const hasRefs = ctx.references.length > 0;
    const hasHighSignalReference = ctx.references.some(
      (ref) => ref.referenceType === 'disclosure' || ref.referenceType === 'earnings'
    );
    const confidence: 'high' | 'medium' | 'low' = hasHighSignalReference ? 'high' : hasRefs ? 'medium' : 'low';
    const insufficientContext = !hasRefs;

    const title = `[Mock] ${ctx.alertName} — ${symbolLabel}`;

    const refLines = ctx.references
      .slice(0, 3)
      .map((r) => {
        const publishedAt = r.publishedAtIso ?? (r.publishedAt ? r.publishedAt.toISOString() : 'N/A');
        return `- [${r.sourceType ?? r.referenceType}] ${r.title} (${publishedAt})`;
      })
      .join('\n');

    const bodyMarkdown = [
      `## ${title}`,
      '',
      `**Symbol:** ${symbolLabel}`,
      `**Alert:** ${ctx.alertName}`,
      `**Type:** ${ctx.alertType ?? 'N/A'}`,
      `**Timeframe:** ${ctx.timeframe ?? 'N/A'}`,
      `**Triggered at:** ${timeInfo}${priceInfo}`,
      '',
      hasRefs
        ? `**Related references (${ctx.references.length}):**\n${refLines}`
        : '> ⚠️ No external references found. Context is limited.',
      '',
      '> ⚠️ This summary was generated by a mock adapter. Replace with a real AI adapter for production.',
    ].join('\n');

    return {
      title,
      bodyMarkdown,
      structuredJson: {
        schema_name: 'alert_reason_summary',
        schema_version: '1.0',
        confidence,
        insufficient_context: insufficientContext,
        payload: {
          what_happened: `${ctx.alertName} アラートが ${symbolLabel} で発火した。`,
          fact_points: [
            '設定されたアラート条件が成立した。',
            ...(ctx.triggerPrice ? [`トリガー価格: ${ctx.triggerPrice}`] : []),
          ],
          reason_hypotheses: hasRefs
            ? ctx.references.slice(0, 2).map((r) => ({
                text: `参照情報（${r.sourceType ?? r.referenceType}）「${r.title}」が背景要因の候補となる可能性。`,
                confidence: 'low' as const,
                reference_ids: [r.id],
              }))
            : [
                {
                  text: '外部参照情報が存在しないため、背景要因は特定できていない。',
                  confidence: 'low' as const,
                  reference_ids: [],
                },
              ],
          watch_points: ['翌営業日の値動きを確認する。'],
          next_actions: ['関連ニュース・開示情報を確認する。'],
          reference_ids: ctx.referenceIds,
        },
      },
      modelName: this.modelName,
      promptVersion: this.promptVersion,
    };
  }
}

// Re-usable singleton for the mock adapter
export const mockAiAdapter: AiAdapter = new MockAiAdapter();
